# Generated by Django 3.2.9 on 2022-04-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fil_id', models.CharField(max_length=3)),
                ('fil_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('argent', models.IntegerField()),
                ('date', models.DateField(blank=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filiere')),
            ],
        ),
    ]
