# Generated by Django 3.2.9 on 2022-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_numero', models.IntegerField(primary_key=True, serialize=False)),
                ('mod_nom', models.CharField(max_length=60)),
            ],
        ),
    ]
