# Generated by Django 3.2.9 on 2022-04-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantParticipeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etudiant')),
                ('par_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
            ],
            options={
                'unique_together': {('par_etudiant', 'par_module')},
            },
        ),
    ]
