# Generated by Django 3.2.9 on 2022-04-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etudiantparticipemodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['fil_name']},
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='api.filiere'),
        ),
    ]
