# Generated by Django 3.2.9 on 2022-04-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_etudiant_filiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={},
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='api.filiere'),
        ),
    ]
